sudo: required
language: go
services:
  - docker
go:
  - "1.10"
env:
  - PATH=$HOME/gopath/bin:$PATH APPPATH=$HOME/gopath/src/github.com/bluehoodie/smoke/ ENVTOKEN=token235
before_install:
  - go get github.com/bluehoodie/smoke
  - docker pull bluehoodie/httpbin
  - docker run -d -p 8000:8000 --rm --name httpbin bluehoodie/httpbin
before_script:
  - go vet ./...
script:
  - smoke -f ${APPPATH}/smoke_test.json -u http://localhost -p 8000 -v
  - docker login -u="$DOCKERHUB_LOGIN" -p="$DOCKERHUB_PASSWORD"
  - cd ${APPPATH}
  - make publish
after_script:
  - docker stop httpbin
