sudo: required
language: go
services:
  - docker
go:
  - "1.10"
env:
  - PATH=$HOME/gopath/bin:$PATH APPPATH=$HOME/gopath/src/github.com/bluehoodie/smoke/ ENVTOKEN=token235
before_install:
  - go get github.com/bluehoodie/smoke
  - docker pull bluehoodie/httpbin
  - docker run -d -p 8000:8000 --rm --name httpbin bluehoodie/httpbin
before_script:
  - go vet ./...
script:
  - smoke -f ${APPPATH}/smoke_test.json -u http://localhost -p 8000 -v
  - cd ${APPPATH}
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_BRANCH
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then make publish; fi
after_script:
  - docker stop httpbin
